#Provide the taskId if you are updating the task
task_id: "DS7GcmnmKZ8hJfNNghuaW88UdNRudH9CYczXtw5TGiYB"
# Name and description of your task
task_name: "web3-revolution"
task_description: 'This is a simple web3 task that returns "Hello, World!"'
task_audit_program: 'dist/main.js'

migrationDescription: "Optimized CPU and RAM usage"

# Network value can be DEVELOPMENT, ARWEAVE or IPFS
task_executable_network: "DEVELOPMENT"

# Total round time of your task: it must be given in slots and each slot is roughly equal to 4ms
round_time: 1500

audit_window: 300
submission_window: 300

# Amounts in KOII

minimum_stake_amount: 2

# total_bounty_amount cannot be greater than bounty_amount_per_round
# total bounty is not accepted in case of update task
total_bounty_amount: 15

bounty_amount_per_round: 1

#Number of times allowed to re-submit the distribution  list in case the distribution list is audited
allowed_failed_distributions: 3

#Space in MBs
space: 1

# Note that the value field in RequirementTag is optional, so it is up to you to include it or not based on your use case.
# To add more global variables and task variables, please refer to the type, value, and description format shown below

author: "Ted"
description: 'This is a simple task that returns "Hello, World!"'
repositoryUrl: "https://github.com/koii-network/hello-world"
imageUrl: "Enter you image URL"
requirementsTags:
  - type: TASK_VARIABLE
    value: SECRET_SPHERON_STORAGE_KEY (required for this task)
    description: "used to connect to Spheron"
  - type: TASK_VARIABLE
    value: "SCRAPING_URL"
    description: "URL from which you want to scrape"
  - type: CPU
    value: "4-core"
  - type: RAM
    value: "5 GB"
  - type: STORAGE
    value: "test"
  - type: NETWORK
    value: "test"
  - type: ARCHITECTURE
    value: "AMD"
  - type: OS
    value: "OSX"